### PR TITLE
fix(props): retrieve only props in the node introspection

### LINKED ISSUE #330: GetProperties: A node can only receive the properties of its introspection

### PR DESCRIPTION
**Pull request by rgallor**
Closes #330

### CODE REVIEW

File: src/astarte/handler.rs [hunk 1]
```diff
@@ -321,6 +320,44 @@ impl DevicePublisher {
...
+            });
+        }
+
+        Ok(())
+    }
+
+    async fn retain_node_props(
+        &self,
+        node_id: NodeId,
+        mut props: Vec<StoredProp>,
```
Comment (joshuachp) [inline src/astarte/handler.rs:350]:
```suggestion
        props: &mut Vec<StoredProp>,
```

File: src/astarte/handler.rs [hunk 2]
```diff
@@ -321,6 +320,44 @@ impl DevicePublisher {
...
+            return Err(AstarteMessageHubError::MissingInterface {
+                interface: interface_name.to_string(),
+                node_id: node_id.into(),
+            });
+        }
+
+        Ok(())
+    }
+
+    async fn retain_node_props(
```
Comment (joshuachp) [inline src/astarte/handler.rs:347]:
```suggestion
    async fn filter_node_props(
```

nit: I think it conveys the action more clearly, but it's not too important

File: src/astarte/handler.rs [hunk 3]
```diff
@@ -321,6 +320,44 @@ impl DevicePublisher {
 
         Ok(())
     }
+
+    // check if the interface is present in the node introspection
+    async fn find_in_introspection(
```
Comment (joshuachp) [inline src/astarte/handler.rs:325]: nit: otherwise, it would return the interface or a boolean

```suggestion
    async fn check_node_has_interface(
```

File: src/error.rs [hunk 4]
```diff
@@ -106,6 +106,19 @@ pub enum AstarteMessageHubError {
     /// Received an invalid ownership enumeration field
     #[error("received an invalid ownership enumeration field, {0}")]
     InvalidProtoOwnership(#[source] UnknownEnumValue),
+
+    /// Interface not present in the node introspection
+    #[error(
+        "interface {} not present in the introspection of node {}",
+        interface,
+        node_id
+    )]
```
Comment (joshuachp) [inline src/error.rs:115]:
```suggestion
    #[error("interface {interface} not present in the introspection of node {node_id}")]
```

File: src/error.rs [hunk 5]
```diff
@@ -129,7 +142,11 @@ impl From<AstarteMessageHubError> for Status {
             | AstarteMessageHubError::Proto(_)
             | AstarteMessageHubError::Uuid(_)
             | AstarteMessageHubError::NodeId(_)
-            | AstarteMessageHubError::InvalidProtoOwnership(_) => Code::InvalidArgument,
+            | AstarteMessageHubError::InvalidProtoOwnership(_)
+            | AstarteMessageHubError::MissingInterface {
+                interface: _,
+                node_id: _,
+            } => Code::InvalidArgument,
```
Comment (joshuachp) [inline src/error.rs:149]:
```suggestion
            | AstarteMessageHubError::MissingInterface {..} => Code::InvalidArgument,
```

File: src/server.rs [hunk 6]
```diff
@@ -165,11 +164,18 @@ where
...
+    ) -> Resp<StoredProperties> {
         let mut props = vec![];
 
         for iface in ifaces_name.names {
-            let iface_props = self.astarte_handler.interface_props(&iface).await?;
+            let iface_props = self
+                .astarte_handler
+                .interface_props(node_id, &iface)
+                .await?;
             props.extend_from_slice(&iface_props);
```
Comment (joshuachp) [inline src/server.rs:179]:
```suggestion
            let iface_props = self
                .astarte_handler
                .interface_props(node_id, &iface)
                .await?;
            props.extend(iface_props);
```

**Review by joshuachp — CHANGES_REQUESTED** [review]

**Review by joshuachp — CHANGES_REQUESTED** [review]
The name of the PR seems incorrect, it should be `fix(props): retrieve only props in the node introspection`

File: src/astarte/handler.rs [hunk 7]
```diff
@@ -321,6 +320,44 @@ impl DevicePublisher {
...
+        &self,
+        node_id: NodeId,
+        interface_name: &str,
+    ) -> Result<(), AstarteMessageHubError> {
+        let node = self.subscribers.read().await;
```
Comment (harlem88) [inline src/astarte/handler.rs:330]: nit: since it should be a list of nodes.
```suggestion
        let nodes = self.subscribers.read().await;
```

File: src/astarte/handler.rs [hunk 8]
```diff
@@ -321,6 +320,44 @@ impl DevicePublisher {
...
+
+        Ok(())
+    }
+
+    async fn retain_node_props(
+        &self,
+        node_id: NodeId,
+        mut props: Vec<StoredProp>,
+    ) -> Result<Vec<StoredProp>, AstarteMessageHubError> {
+        let node = self.subscribers.read().await;
```
Comment (harlem88) [inline src/astarte/handler.rs:352]: same
```suggestion
        let nodes = self.subscribers.read().await;
```

**Review by harlem88 — CHANGES_REQUESTED** [review]

File: src/astarte/handler.rs [hunk 9]
```diff
@@ -508,32 +545,82 @@ impl AstartePublisher for DevicePublisher {
...
+        Ok(props)
     }
 
-    fn device_props(&self) -> impl Future<Output = Result<Vec<StoredProp>, AstarteError>> + Send {
-        self.client.device_props()
+    async fn device_props(
+        &self,
+        node_id: NodeId,
+    ) -> Result<Vec<StoredProp>, AstarteMessageHubError> {
+        // we first need to retrieve all the properties and then filter
```
Comment (harlem88) [inline src/astarte/handler.rs:596]:
```suggestion
        // we first need to retrieve all the device properties and then filter
```

File: src/astarte/handler.rs [hunk 10]
```diff
@@ -508,32 +545,82 @@ impl AstartePublisher for DevicePublisher {
...
+        Ok(props)
     }
 
-    fn server_props(&self) -> impl Future<Output = Result<Vec<StoredProp>, AstarteError>> + Send {
-        self.client.server_props()
+    async fn server_props(
+        &self,
+        node_id: NodeId,
+    ) -> Result<Vec<StoredProp>, AstarteMessageHubError> {
+        // we first need to retrieve all the properties and then filter
```
Comment (harlem88) [inline src/astarte/handler.rs:613]:
```suggestion
        // we first need to retrieve all the server properties and then filter
```

**Review by harlem88 — CHANGES_REQUESTED** [review]

**Review by harlem88 — APPROVED** [review]

**Review by joshuachp — APPROVED** [review]
